/*//////////////////////////////////////////////////////////////////
////     The SKIRT project -- advanced radiative transfer       ////
////       © Astronomical Observatory, Ghent University         ////
///////////////////////////////////////////////////////////////// */

#ifndef FSPSvarIMFcontSFHSED_HPP
#define FSPSvarIMFcontSFHSED_HPP

#include "FamilySED.hpp"

////////////////////////////////////////////////////////////////////

/** FSPSvarIMFcontSFHSED is a class that represents spectral energy distributions of composite stellar populations
    (CSPs) forming stars at a constant rate over ten Myr. The templates are parameterized on metallicity and IMF slope and 
    generated by the FSPS code presented by Conroy, Gunn, & White (2009, ApJ, 699, 486) and Conroy & Gunn (2010, ApJ, 712, 833).
    See the FSPSvarIMFcontSFHSEDFamilyclass for more information. */
class FSPSvarIMFcontSFHSED : public FamilySED
{
    ITEM_CONCRETE(FSPSvarIMFcontSFHSED, FamilySED, "an FSPS variable-IMF composite stellar population SED constantly forming stars over ten Myr")

        PROPERTY_DOUBLE(metallicity, "the metallicity of the SSP")
        ATTRIBUTE_MIN_VALUE(metallicity, "[0.0001")
        ATTRIBUTE_MAX_VALUE(metallicity, "0.05]")
        ATTRIBUTE_DEFAULT_VALUE(metallicity, "0.02")

        PROPERTY_DOUBLE(alpha, "the high-mass IMF slope of the SSP")
        ATTRIBUTE_MIN_VALUE(alpha, "[1")
        ATTRIBUTE_MAX_VALUE(alpha, "2.3]")
        ATTRIBUTE_DEFAULT_VALUE(alpha, "2.3")

    ITEM_END()

    //============= Construction - Setup - Destruction =============

protected:
    /** This function returns a newly created SEDFamily object (which is already hooked into the
        simulation item hierachy so it will be automatically deleted) and stores the parameters for
        the specific %SED configured by the user in the specified array. */
    const SEDFamily* getFamilyAndParameters(Array& parameters) override;
};

////////////////////////////////////////////////////////////////////

#endif
