/*//////////////////////////////////////////////////////////////////
////     The SKIRT project -- advanced radiative transfer       ////
////       © Astronomical Observatory, Ghent University         ////
///////////////////////////////////////////////////////////////// */

#ifndef FSPSvarIMFSED_HPP
#define FSPSvarIMFSED_HPP

#include "FamilySED.hpp"

////////////////////////////////////////////////////////////////////

/** FSPSvarIMFSED is a class that represents spectral energy distributions of simple stellar populations
    (SSPs), parameterized on metallicity, age and IMF slope, generated by the FSPS code presented by Conroy,
    Gunn, & White (2009, ApJ, 699, 486) and Conroy & Gunn (2010, ApJ, 712, 833). See the FSPSvarIMFSEDFamily
    class for more information. */
class FSPSvarIMFSED : public FamilySED
{
    ITEM_CONCRETE(FSPSvarIMFSED, FamilySED, "an FSPS variable-IMF simple stellar population SED")

        PROPERTY_DOUBLE(metallicity, "the metallicity of the SSP")
        ATTRIBUTE_MIN_VALUE(metallicity, "[0.0001")
        ATTRIBUTE_MAX_VALUE(metallicity, "0.05]")
        ATTRIBUTE_DEFAULT_VALUE(metallicity, "0.02")

        PROPERTY_DOUBLE(age, "the age of the SSP")
        ATTRIBUTE_QUANTITY(age, "time")
        ATTRIBUTE_MIN_VALUE(age, "[0 Gyr")
        ATTRIBUTE_MAX_VALUE(age, "20 Gyr]")
        ATTRIBUTE_DEFAULT_VALUE(age, "5 Gyr")

    ITEM_END()

    //============= Construction - Setup - Destruction =============

protected:
    /** This function returns a newly created SEDFamily object (which is already hooked into the
        simulation item hierachy so it will be automatically deleted) and stores the parameters for
        the specific %SED configured by the user in the specified array. */
    const SEDFamily* getFamilyAndParameters(Array& parameters) override;
};

////////////////////////////////////////////////////////////////////

#endif
